# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2lPbwYlzaFWOm33JG5y3P90MdKweYoA
"""

import streamlit as st
from ultralytics import YOLO
import os

st.title("Custom Object Detection with YOLO")

# Load your custom YOLO model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Sidebar for user input
st.sidebar.header("Model Inference")

# User input for image or image folder
inference_type = st.sidebar.radio("Choose Inference Type:", ["Single Image", "Image Folder"])

if inference_type == "Single Image":
    image_path = st.sidebar.text_input("Image Path (e.g., /path/to/your/image.jpg)")
    image_paths = [image_path] if image_path else []
else:
    folder_path = st.sidebar.text_input("Image Folder Path (e.g., /path/to/your/folder)")
    image_paths = [os.path.join(folder_path, filename) for filename in os.listdir(folder_path) if filename.lower().endswith((".jpg", ".jpeg", ".png"))]

if st.sidebar.button("Detect Objects"):
    if image_paths:
        col1, col2 = st.columns(2)
        for image_path in image_paths:
            result = model.predict(image_path)
            col1.image(result[0], caption=f"Detected Objects in {os.path.basename(image_path)}", use_column_width=True)
            col2.image(result.save()[0], caption=f"Result Image for {os.path.basename(image_path)}", use_column_width=True)
        st.success("Object detection and result image creation complete.")
    else:
        st.warning("No images found for detection.")

# Export model
if st.sidebar.button("Export Model"):
    model.export(format="pb")
    st.success("Model export complete.")

st.write("This is a Streamlit app for your custom YOLO object detection model.")